package sk.portugal.leksi.kskimp;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import sk.portugal.leksi.kskimp.service.KskImportService;

import java.util.Arrays;

public class KskImport {

    private static String[] words = {

            "zobák",
            "zrak",
            "zvyk",
            "zadusenie",
            "zahanbiť",
            "zahasiť",
            "zahnúť",
            "zahraničie",
            "zajať",
            "zajatec",
            "zakázať",
            "zakriviť",
            "zakročiť",
            "založiť",
            "zamestnať",
            "zamestnať sa",
            "zamestnanie",
            "zametať",
            "zamiesť",
            "zamilovať sa",
            "zamilovaný",
            "zamraziť",
            "zapáchať",
            "zapliesť",
            "zapletať",
            "zapríčiniť",
            "zarobiť",
            "zaručiť",
            "zasnúbiť sa",
            "zastupovať",
            "zaujímať sa",
            "zaujímať",
            "zábava",
            "záclona",
            "závažie",
            "záves",
            "závidieť",
            "zbabelý",
            "zbabelec",
            "zbierka",
            "zbor",
            "zdvorilý",
            "zlatý",
            "zjesť",
            "zlepšiť",
            "zlosť",
            "parketa",
            "pazúr",
            "pašerák",
            "pašie",
            "pažravý",
            "pád",
            "pečený",
            "pec",
            "pediater",
            "pediaria",
            "pekáč",
            "pekár",
            "penivý",
            "pestovať",
            "pianista",
            "pilier",
            "pinzeta",
            "pitvať",
            "pitva",
            "píla",
            "plantáž",
            "plaziť sa",
            "plášť",
            "ples",
            "plnka",
            "plus"
};

    public static void main(String[] args) {

        ApplicationContext ctx = new ClassPathXmlApplicationContext("config/beans.xml");
        KskImportService importService = (KskImportService) ctx.getBean("kskImportService");


        importService.generateImport(Arrays.asList(words));

/*        PrintStream out = null;
        try {
            out = new PrintStream(new FileOutputStream("output.txt"));
        } catch (FileNotFoundException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
        System.setOut(out);*/

        //Printer.printAll(words);

        //System.out.println("words: " + words.size());
    }
}


    /*private static String[] words = {"priamo", "riešiť", "správať sa", "tamto", "uspokojiť", "výhodný",
            "priateľ", "robiť", "spraviť", "tanier", "usporiadať", "vyhrať",
            "približne", "roh", "správny", "taška", "ústa", "vyhrážať sa",
            "príbor", "rovina", "spresniť", "ťažký", "ústredňa", "vychádzať",
            "príčina", "rovno", "sprcha", "ťažko", "usušiť", "vyjsť",
            "pridať", "rovný", "spustiť", "teda", "ušetriť", "výklad",
            "pridať sa", "rozbehnúť sa", "spýtať sa", "tehotná", "ušiť", "vykĺbiť",
            "priemerný", "rozbiť", "srdce", "tekutina", "útes", "vykonať",
            "priepasť", "rozdeliť", "stačiť", "telo", "utiecť", "vyľakať",
            "priestor", "rozliať", "stan", "telocvična", "útočník", "výlet",
            "priestupok", "rozložiť", "stanica", "ten", "utopiť sa", "vyletieť",
            "prihlásiť sa", "rozopnúť", "stánok", "tá", "uvedmoiť si", "vyliať",
            "prijať", "rozpadnúť sa", "starosť", "tenis", "uviazať", "vyliečiť",
            "príjemný", "rozprávať", "stáť", "tento", "uvoľniť", "vyliečenie",
            "prikázať", "rozprávať sa", "stať sa", "teplý", "uvoľniť sa", "vyliečiť sa",
            "prikryť", "rozsypať", "stav", "terasa", "úzky", "vyliezť",
            "prikrývka", "rozšíriť", "staviť", "termín", "už", "vyložiť",
            "prilepiť", "rozšíriť sa", "sťažeň", "tešiť sa", "v, vo", "vymeniť",
            "príliš", "roztiahnuť", "sťažovať sa", "tiecť", "vak", "vymyslieť",
            "príloha", "roztopiť", "sťažovať", "ticho", "variť", "vymyslieť si",
            "priložiť", "roztopiť sa", "stena", "tisíc", "vás", "vynikajúci",
            "prinútiť", "roztrhnúť", "stĺp", "tlačiť", "váš", "vynoriť sa",
            "prípad", "rozumieť", "sto", "tlačiť sa", "vážiť", "vypiť",
            "pripevniť", "rozviazať", "stojan", "tlak", "vážiť si", "vyplniť",
            "pripojiť", "rôzny", "stolička", "tma", "väzenie", "vypnúť",
            "pripojiť sa", "ručný", "stiahnuť", "tmavý", "včas", "vypovedať",
            "prispieť", "rukavica", "stiahnuť sa", "točiť", "vec", "výprava",
            "prísť", "rukojemník", "stlačiť", "točiť sa", "večer", "vyprázdniť",
            "pristáť", "rušiť", "stlmiť", "topiť", "večera", "vypustiť",
            "pristátie", "ružový", "stolný", "topiť sa", "večerať", "vyriešiť",
            "prístroj", "ryba", "stopa", "tovar", "vedenie", "vyrovnať",
            "prístupný", "rýchlik", "stopovať", "trafiť", "vedieť", "vyrovnať sa",
            "pritiahnuť", "s, so", "stornovať", "tragédia", "vedúci", "vysávač",
            "prítomný", "sadnúť", "strana", "traktor", "veľa", "vysávať",
            "príves", "sadzba", "strašný", "trasa", "veľký", "vyskočiť",
            "prízemie", "sám", "stratiť", "trať", "veľmi", "vyskúšať",
            "príznak", "samozrejme", "stratiť sa", "tráva", "veľvyslanec", "výsledok",
            "priznať", "sankcia", "strava", "tráviť", "veľvyslanectvo", "výsluch",
            "priznať sa", "sebe", "stred", "trest", "ventilátor", "vysoký",
            "prosiť", "sem", "stredisko", "trezor", "veriť", "vysťahovať sa",
            "proti", "servis", "stredný", "trhať", "vesta", "výstava",
            "prst", "sestra", "stretnúť", "trieda", "vhodný", "vystrašiť",
            "prsteň", "sezóna", "stretnúť sa", "trochu", "vchod", "vystreliť",
            "pršať", "schod", "striedať", "trvať", "Vianoce", "vystriedať",
            "prúd", "schopný", "striekačka", "tu", "vidiek", "výstroj",
            "prudký", "schránka", "strieľať", "tvrdý", "vidieť", "vystúpiť",
            "pruh", "schváliť", "stroj", "turista", "vidieť sa", "vysvetliť",
            "prút", "siahnuť", "strom", "tvár", "viesť", "vysvetliť sa",
            "prvý", "sieť", "stroskotať", "tvoj", "vila", "vyšetriť",
            "pstruh", "signál", "studený", "tvoja", "vjazd", "zoznam",
            "pulóver", "silný", "stúpať", "tvrdiť", "vlámanie", "zoznámiť sa",
            "pult", "situácia", "súčasne", "tvrdý", "vlas", "zranený",
            "pustiť", "skákať", "súhlasiť", "tyč", "vlastniť", "zraziť",
            "pustiť sa", "skala", "súprava", "týkať sa", "vlastný", "zraziť sa",
            "puška", "skočiť", "súrny", "typ", "vlek", "zrážka",
            "púšť", "skomplikovať", "surový", "ublížiť", "vliecť", "zrelý",
            "púť", "skomplikovať sa", "susedný", "ubytovať sa", "vlna", "zrušiť",
            "radiť", "skončiť", "súťaž", "učesať", "vnuk", "zrútiť sa",
            "raja", "skoro", "svah", "učesať sa", "vnútrozemie", "zrýchliť",
            "rak", "skôr", "sveter", "učiť", "vodič", "zub",
            "rakva", "skryť", "svetlý", "učiť sa", "vodopád", "zubár",
            "rám", "skryť sa", "sviatok", "učiteľ", "vojsť", "priateľstvo",
            "rampa", "skrývať", "sviečka", "udalosť", "volant", "priateľský",
            "rásť", "skrývať sa", "svietiť", "údolie", "volať", "pulz",
            "rastlina", "skúsiť", "svrbieť", "udrieť", "volať sa", "pútnik",
            "rebrík", "skutočný", "syn", "udržať", "voľný", "putovanie",
            "recepcia", "skutok", "šatka", "uhasiť", "voňať", "opýtať sa",
            "recept", "skvelý", "šatňa", "uhlie", "predtým", "registrovať",
            "reč", "slabý", "šaty", "uistiť", "voziť", "rozbiť sa",
            "regál", "sladký", "šéf", "uistiť sa", "vracať", "rozrušiť",
            "registrácia", "slanina", "šek", "ukázať", "vrátane", "rozrušenie",
            "reklamovať", "slávnosť", "šikovný", "ukončiť", "vrátiť", "sieň",
            "remeň", "sledovať", "široký", "ukradnúť", "vraziť", "skok",
            "republika", "slepý", "šiť", "ukryť", "vreckovka", "stráž",
            "rešpektovať", "slimák", "škatuľa", "uložiť", "vrhnúť sa", "stretnutie",
            "revízor", "slobodný", "škoda", "umrieť", "vrchnák", "striekať",
            "porezať sa", "slovo", "škola", "úmysel", "vrchol", "svetlovlasý",
            "rezať", "slučka", "škriabať", "úmyselne", "vrtuľník", "svetlomet",
            "rezeň", "smer", "zvierať", "uniesť", "vstať", "svetadiel",
            "rezerva", "smotana", "šnúra", "uplatniť", "vstup", "svrbenie",
            "rezervovať", "snažiť sa", "šoférovať", "upevniť", "vtupenka", "šofér",
            "riasa", "snežiť", "šokovať", "úplný", "vstupné", "vyhodiť",
            "rieka", "socha", "španielčina", "upokojiť", "všetci", "výhodný",
            "spomenúť si", "soľnička", "šperk", "upokojiť sa", "všetko", "vydať sa",
            "spôsob", "sopka", "špička", "upozorniť", "všimnúť si", "vydržat",
            "spôsobiť", "spadnúť", "špinavý", "upratať", "vták", "výhľad",
            "správa", "spáliť", "štart", "úrad", "vtip", "vyhnať",
            "takto", "spáliť sa", "študent", "úradník", "vy", "vyhnúť sa",
            "takže", "spať", "štvorec", "úraz", "vybaviť", "usadiť",
            "tam", "späť", "štvorcový", "uraziť", "výborný", "usadiť sa",
            "tamten", "splniť", "štvrť", "uraziť sa", "vybrať", "tak",
            "úschovňa", "spodný", "šumivý", "urážka", "vybuchnúť", "taký",
            "usliovať sa", "spojiť", "táboriť", "určiť", "vyčistiť", "spolu",
            "uskladniť", "spojiť sa", "tabuľa", "určite", "vydanie", "spomenúť",
            "usmiať sa", "spoločný", "ťahať", "urobiť", "vydať"};

    private static String[] words = {"preskúmanie",
            "presný",
            "presnosť",
            "prestieradlo",
            "presunúť",
            "presunúť sa",
            "presun",
            "presvedčiť",
            "presvedčiť sa",
            "pretlmočiť",
            "pretože",
            "prevaha",
            "prevažovať",
            "prevládať",
            "prevrátiť",
            "prevrhnúť sa",
            "prevýšiť",
            "prezliekareň",
            "prezradiť",
            "preškrtnúť",
            "prežiť",
            "prežrieť",
            "prežúvať",
            "pri",
            "pričleniť",
            "pričleniť sa",
            "priľahlý",
            "priľnavý",
            "priľnúť",
            "priťahovať",
            "priať",
            "priať si",
            "priamy",
            "prianie",
            "priateľskosť",
            "pribehnúť",
            "priblížiť",
            "priblížiť sa",
            "pribrať",
            "pribúdať",
            "prichystať",
            "prichýliť",
            "prideliť",
            "pridružiť sa",
            "priebeh",
            "priekopnícky",
            "priekopník",
            "prieliv",
            "prieplav",
            "priepustka",
            "priestranný",
            "prifarbiť",
            "prihodiť sa",
            "prihriať",
            "prijatie",
            "prikročiť",
            "prikývnuť",
            "prilepiť sa",
            "priliehavý",
            "prilipnúť",
            "priložený",
            "primitívny",
            "prinútiť sa",
            "priorita",
            "pripiť",
            "pripisovať",
            "pripodobniť",
            "pripojený",
            "pripomenúť",
            "pripomenúť si",
            "pripomienka",
            "pripravený",
            "pripraviť sa",
            "pripustiť",
            "pripútať",
            "prirodzene",
            "prirodzený",
            "prirovnať",
            "prisľúbiť",
            "prisťahovať sa",
            "prisťahovalecký",
            "prisladiť",
            "prispievať",
            "prispôsobiť",
            "prispôsobiť sa",
            "prisvedčiť",
            "pritakať",
            "pritakanie",
            "priveľmi",
            "priviazať",
            "privilegovať",
            "privinúť",
            "privítať",
            "privítanie",
            "privoliť",
            "príbeh",
            "príboj",
            "príborník",
            "prídavný",
            "príhoda",
            "prímorský",
            "prípitok",
            "prísľub",
            "prísada",
            "prísaha",
            "príslušný",
            "prísny",
            "prístrešok",
            "prítok",
            "prívesok",
            "prívod",
            "prívrženec",
            "procesia",
            "produkovať",
            "profesor",
            "profitovať",
            "programovanie",
            "projektor",
            "projekt ",
            "projektovať",
            "propaganda",
            "propagácia",
            "prospekt",
            "prostý",
            "protijed",
            "protiklad",
            "protirečenie",
            "protirečiť",
            "protirečiť si",
            "protivník",
            "protokol",
            "prototyp",
            "provincia",
            "provokovať",
            "prstenec",
            "íngreme",
            "pružina",
            "pružný",
            "prúdiť",
            "psí",
            "psychiater",
            "psychiatria",
            "psychológ",
            "publikácia",
            "publikovať",
            "publikum",
            "puding",
            "pukance",
            "puklina",
            "punč",
            "purpurový",
            "pustatina",
            "pustovník",
            "pustý",
            "puto",
            "puk",
            "pykať",
            "pyramída",
            "pyšný",
            "pýcha",
            "pýšiť sa",
            "pšenica",
            "rabín",
            "rada",
            "radar",
            "radca",
            "radiátor",
            "radikál",
            "radovať sa",
            "radšej",
            "ragby",
            "rajčina",
            "raketa",
            "Rakúsko",
            "rameno",
            "ramienko",
            "raniť",
            "rasa",
            "rast",
            "rastlinný",
            "ražeň",
            "rátať",
            "realizovať",
            "realizovať sa",
            "recesia",
            "recitovať",
            "recyklovať",
            "redigovať",
            "redukcia",
            "referovať",
            "reflektor",
            "reformátor",
            "regenerácia",
            "regulovať",
            "rehoľa",
            "relaxovať",
            "rely",
            "remizovať",
            "renovovať",
            "reportér",
            "reprezentant",
            "reprezentácia",
            "reprezentovanie",
            "reprodukovať",
            "reproduktor",
            "reputácia",
            "resumé",
            "retiazka",
            "reuma",
            "rev",
            "revať",
            "revolta",
            "revue",
            "rez",
            "rezák",
            "rezký",
            "reštaurovať",
            "režisér",
            "režírovať",
            "riť",
            "riadiť",
            "riaditeľ",
            "riaditeľstvo",
            "riadok",
            "riečka",
            "riediť",
            "riedky",
            "ring",
            "riskovať",
            "rival",
            "rivalita",
            "ríbezľa",
            "roľa",
            "rod",
            "rodiť",
            "rodisko",
            "rodný",
            "rohožka",
            "roklina",
            "rokovať",
            "rokovanie",
            "ropa",
            "ropný",
            "ropucha",
            "rotunda",
            "rovnako",
            "rovnobežka",
            "rovnobežný",
            "rovnováha",
            "rozčarovať",
            "rozčleniť",
            "rozčúliť",
            "rozčúliť sa",
            "rozbaliť",
            "rozdať",
            "rozdeľovač",
            "rozdrobiť",
            "rozdrviť",
            "rozhnevať",
            "rozhnevať sa",
            "rozhodca",
            "rozhodnúť",
            "rozhodnúť sa",
            "rozhodný",
            "rozhorčiť sa",
            "rozhorčenie",
            "rozhovor",
            "rozhrýzť",
            "rozísť sa",
            "rozkaz",
            "rozkázať",
            "rozklad",
            "rozkladať sa",
            "rozlíšiť",
            "rozloha",
            "rozluka",
            "rozlúčenie",
            "rozlúčka",
            "rozmaznávať",
            "rozmeniť",
            "rozmliaždiť",
            "rozmnožiť",
            "rozmnožovať",
            "rozmnožovať sa",
            "rozmnožovanie",
            "rozmýšľať",
            "roznášať",
            "rozniesť",
            "rozniesť sa",
            "rozoznať",
            "rozpŕchnuť sa",
            "rozpad",
            "rozpínať sa",
            "rozplynúť sa",
            "rozpor",
            "rozpoznať",
            "rozprávač",
            "rozprávanie",
            "rozprestierať sa",
            "rozpestrieť",
            "rozptýliť",
            "rozptýliť sa",
            "rozpustiť",
            "rozpustiť sa",
            "rozsah",
            "rozsiahly",
            "rozsudok",
            "rozsypať",
            "roztaviť",
            "roztaviť sa",
            "roztrúsiť",
            "roztvoriť",
            "rozum",
            "rozveseliť",
            "rozvidnievať sa",
            "rozviesť sa",
            "rozvinúť",
            "rozvinúť sa",
            "rozvíjať",
            "rozvíjať sa",
            "rozzúriť",
            "rozzúriť sa",
            "rozšíriť",
            "roštenka",
            "röntgenogram",
            "ručička",
            "ruch",
            "rukopis",
            "rukoväť",
            "Rumunsko",
            "rušný",
            "ryť",
            "rypák",
            "rysovať",
            "rytec",
            "rytier",
            "rytina",
            "sčítať",
            "sčítaný",
            "sľúbiť",
            "sťahovanie",
            "sťažiť",
            "sať",
            "sad",
            "sadenie",
            "sadlo",
            "safari",
            "sakristia",
            "salón",
            "salsa",
            "salto",
            "samba",
            "samec",
            "samoľúby",
            "samohláska",
            "samostatnosť",
            "samotár",
            "samotársky",
            "samotný",
            "sanatórium",
            "saxofón",
            "scediť",
            "scenár",
            "scenárista",
            "scéna",
            "scénograf",
            "schéma",
            "schizofrénia",
            "schnúť",
            "schopnosť",
            "schovať"};

private static String[] words = {"absolvovať", "adresa", "advokát", "ahoj", "aj", "ak ", "ako", "aký", "alebo", "ambasáda",
            "antický", "antikoncepcia", "asi", "auto", "babka", "balón", "banka", "bankovka", "baňa", "bahno,baliť", "balón", " baran",
            "báť sa", "batožina", "baviť sa", "baviť", "bazén", "bezvedomie", "bežať", "bežný", "bielizeň", "biely", "biftek", "biť sa",
            "bitka", "blato", "blázon", "bledý", "blesk", "blízky", "blokovať", "blúzka", "bodnúť", "boh", "bojovať", "bok", "bolest",
            "bolestný", "brada", "brána", "brániť", "brániť sa", "brať", "breh", "brucho", "brzdiť", "bufet", "búchať ", "búrka", "bydlisko",
            "byt", "byť", "bývalý", "celkom", "	cenný", "centrum", "cesta", "cestovať", "cez", "cibuľa", "cieľ", "cítiť", "cítiť sa",
            "čudný", "cudzinec", "cukrík", "cukrovka", "cúvať", "cúvnuť", "cvičiť", "cisterna", "citovať", "cválať", "cvičenie", "cyklista",
            "cyklus", "čaj", "čakan", "časť", "často", "častý", "čašník", "černoch", "červený", "čiara", "čistý", "čižma", "člen", "čln",
            "čo", "čokoláda", "čudovať sa", "Čech", "čajka", "ďalej", "ďaleko", "ďaleký", "ďalší", "dar", "dátum", "dávno", "dedko", "defekt",
            "dejiny", "deka", "deliť", "deliť sa", "denne", "detail", "deväť", "deväťdesiat", "deväťsto", "diaľnica", "dieťa", "diskusia",
            "diskutovať", "divák", "divoký", "dlhovať", "dno", "do", "doba", "dobre", "dobrý", "dodatočný", "dodržať", "dodržiavať", "dohoda",
            "dohodnúť sa", "dokázať", "dokončiť", "dole", "dom", "domáci", "domorodec", "domov", "donútiť", "dopĺňať", "dopoludnie", "doprava",
            "dopredu", "doručiť", "doska", "dostať", "dostať sa", "dostihnúť", "dotknúť sa", "dovidenia", "doviezť", "dovoliť", "dozadu",
            "dozor", "dôjsť", "dôverný", "dôvod", "dráha", "drahý", "drobné", "drôt", "drsný", "druh", "drzý", "držadlo", "držať", "držať sa",
            "dúfať", "dusiť sa", "dva", "dvadsať", "dvanásť", "dýchať", "džús", "ekonómia", "električka", "elektrický", "energia", "Európan",
            "európsky", "existovať", "falošný", "farba", "filé", "firma", "fľak", "fúkať", "fungovať", "gól", "golier", "gombík", "guľa",
            "guma", "had", "hádať sa", "hanbiť sa", "handra", "havária", "helikoptéra", "hľadať", "hladký", "hladný", "hlava", "hlavne",
            "hlavný", "hlboký", "hliadka", "hluk", "hneď", "hnevať sa", "hnevať", "hniezdo", "hoci", "hodina", "hodiť", "hodiť sa", "hojdať sa",
            "holiť", "holiť sa", "holý", "horčica", "hore", "horieť", "horký", "horúci", "horúčava", "hosť", "hostiteľ", "hotový", "hovno",
            "hovor", "hovoriť", "hra", "hračka", "hrach", "hrať", "hrať sa", "hrebeň", "hrob", "hrubý", "huba", "hudobný", "humor", "husle",
            "hustý", "hviezda", "hýbať", "hýbať sa", "chalupa", "chaos", "chcieť", "chlap", "chlp", "chodba", "chodec", "chodiť", "chodník",
            "choroba", "chovať", "chrbát", "chrípka", "chudák", "chudý", "chutiť", "chváliť", "chváliť sa", "chvíľa", "chvost", "chyba",
            "chýbať", "chytať", "chytiť", "iba", "ihrisko", "infarkt", "infekcia", "informovať", "injekcia", "iný", "inzerát", "ísť", "iste",
            "istý", "izolovať", "ja", "jama", "jasný", "jazdiť", "jazero", "jedenásť", "jediný", "jedlo", "jeho", "jej", "jesť", "k", "kabelka",
            "kačica", "kaňon", "kapusta", "karta", "kašlať", "káva", "kaviareň", "keby", "keď", "kedysi", "kel", "kempovať", "kilogram", "kino",
            "kladivo", "klavír", "kĺb", "klenotníctvo", "klinec", "klobása", "klobúk", "klopať", "klub", "kľučka", "kohútik", "koláč", "koleso",
            "koľko", "kolo", "komár", "kompletný", " komplikovaný", "komunikácia", "konár", " konať", "koncert", "kondóm", "konečne", "kontakt",
            "konzerva", "kopať", "kópia", "korčuľa", "korčuľovať sa", "koruna", "košeľa", "kov", "krab", "krádež", "kraj", "krajina", "krásny",
            "krém", "kresliť", "kreveta", "krok", "kruh", "krúpa", "krvácať", "kto", "ktorý", "ktorýkoľvek", "kufor", "kuchyňa", "kapele",
            "kúpiť", "kurz", "kým", "kyselina", "kyslý", "lampa", "lano", "látka", "len", "lep", "lepší", "let", "letieť", "ležať", "liezť",
            "línia", "linka", "list", "lístok", "liter", "lokomotíva", "lopta", "loviť", "ľudový", "lúpež", "ľutovať", "lyžica", "majetok",
            "majiteľ", "majonéza", "maľovať", "mandarínka", "masť", "mäkký", "mäso", "mäta", "medzitým", "menej", "mesiac", "mesto", "meter"
    };

    private static String[] words = {"schudnúť",
            "schudobnieť",
            "schvaľovať",
            "presiahnuť",
            "sebec",
            "sebecký",
            "sedatívum",
            "sedlo",
            "sedmokráska",
            "sekať",
            "sekcia",
            "sekretárka",
            "sekt",
            "sekundárny",
            "semenník",
            "semeno",
            "seminár",
            "sen",
            "senior",
            "serenáda",
            "seriózny",
            "severovýchodný",
            "servírovať",
            "Severoameričan",
            "severoamerický",
            "severozápad",
            "severozápadný",
            "sféra",
            "sformovať",
            "sformovaný",
            "siať",
            "sila",
            "simulovať",
            "sirota",
            "situovať",
            "sídliť",
            "sídliaci",
            "skladať",
            "skladateľ",
            "sklamať",
            "sklamanie",
            "skloniť sa",
            "skláňať sa",
            "skomponovať",
            "skorumpovaný",
            "skrachovať",
            "skrátiť",
            "skrášliť",
            "skriviť",
            "skrkvať",
            "skrotiť",
            "skrotnúť",
            "skrýša",
            "skutočne",
            "skutočnosť",
            "skúmať",
            "skúška",
            "skysnúť",
            "slabosť",
            "sladkosť",
            "slama",
            "sláčik",
            "sláva",
            "sláviť",
            "slávka",
            "sled",
            "slepec",
            "slezina",
            "slintať",
            "sloh",
            "slonovina",
            "Slovensko",
            "Slovinsko",
            "sluch",
            "slušný",
            "slúžiť",
            "smažiť",
            "smieť",
            "smiešny",
            "smrečina",
            "smrteľný",
            "snaha",
            "sob",
            "sochárstvo",
            "sociológia",
            "sociológ ",
            "sólo",
            "spariť",
            "spáchať",
            "sperma",
            "spev",
            "spievať",
            "spisovateľ",
            "splachovač",
            "splodiť",
            "spojenectvo",
            "spojenie",
            "spoločník",
            "spoluhláska",
            "spolunažívať",
            "spolupracovať",
            "spolužiak",
            "spomienka",
            "spor",
            "sporiť",
            "spotiť sa",
            "spotrebovať",
            "spoznať",
            "spozorovať",
            "spravodlivo",
            "spravodlivý",
            "spráchnivieť",
            "správanie",
            "správne",
            "sprevádzať",
            "sprostý",
            "sprostosť",
            "Srb",
            "Srbsko",
            "srbčina",
            "srbský",
            "srvátka",
            "stagnovať",
            "stan",
            "stanovať",
            "stanoviť",
            "starať sa",
            "starec",
            "starnúť",
            "starobylý",
            "starostlivosť",
            "staroveký",
            "stavať",
            "stavba",
            "stavebníctvo",
            "stále",
            "stenať",
            "sterlizácia",
            "sterlizovať",
            "sterilnosť",
            "stimulovať",
            "stisnúť",
            "stíchnuť",
            "stlačený",
            "stmavnúť",
            "stmievať sa",
            "stmievanie",
            "stojan",
            "stonať",
            "stopky",
            "stotina",
            "strata",
            "stráviť",
            "strela",
            "strelec",
            "streliť",
            "strihať",
            "stroskotanec",
            "stroskotanie",
            "stručný",
            "struna",
            "strúhať",
            "stučnieť",
            "stuchlina",
            "stuha",
            "stupnica",
            "stvoriť",
            "suka",
            "surfovať",
            "sušiť",
            "súčasný",
            "súťažiť",
            "súcit",
            "súhlas",
            "súmrak",
            "súper",
            "súperenie",
            "súperiť",
            "sústrediť",
            "sústrediť sa",
            "súvislosť",
            "svedčiť",
            "sviňa",
            "svieži",
            "svitať",
            "svitanie",
            "svokra",
            "symbol",
            "sympatia",
            "sympatizovať"};


            */

/*
    private static String[] words = {"advokát", "aféra", "agresia", "agresívny", "aktovka", "aliancia", "analfabet", "analyzovať",
            "anestézia", "anténa", "apartmán", "aplaudovať", "aplikovať", "arašíd", "argument", "argumentovať", "aristokracia",
            "aristokrat", "artikulácia", "artikulovať", "asistent", "asistovať", "ateista", "autor", "átrium", "balet", "balvan",
            "bandita", "banket", "bariéra", "barla", "barón", "batéria", "bábä", "bádať", "bál", "bedeker", "beh", "behať", "besnota",
            "bezočivý", "bežec", "béžový", "bicie", "bilancia", "bilión", "bisexuál", "blok", "bobuľa", "box", "boxer", "bozkávať",
            "bralo", "brankár", "brblať", "brechať", "bremeno", "britva", "bronchitída", "brožúra", "bubienok", "bublina", "budhista",
            "budiť", "bunka", "burza", "buržoázia", "cap", "cediť", "cela", "celkový", "celok", "cement", "ceniť si", "centrálny",
            "cenzurovať", "cereálie", "certifikát", "cesto", "chaluha", "chamtivosť", "chápať", "chladený", "chlpatý", "Chmeľ",
            "chobot", "chór", "chrániť", "chrápať", "chrbtica", "chudnúť",
            "priamo", "riešiť", "správať sa", "tamto", "uspokojiť", "výhodný",
            "priateľ", "robiť", "spraviť", "tanier", "usporiadať", "vyhrať",
            "približne", "roh", "správny", "taška", "ústa", "vyhrážať sa",
            "príbor", "rovina", "spresniť", "ťažký", "ústredňa", "vychádzať",
            "príčina", "rovno", "sprcha", "ťažko", "usušiť", "vyjsť",
            "pridať", "rovný", "spustiť", "teda", "ušetriť", "výklad",
            "pridať sa", "rozbehnúť sa", "spýtať sa", "tehotná", "ušiť", "vykĺbiť",
            "priemerný", "rozbiť", "srdce", "tekutina", "útes", "vykonať",
            "priepasť", "rozdeliť", "stačiť", "telo", "utiecť", "vyľakať",
            "priestor", "rozliať", "stan", "telocvična", "útočník", "výlet",
            "priestupok", "rozložiť", "stanica", "ten", "utopiť sa", "vyletieť",
            "prihlásiť sa", "rozopnúť", "stánok", "tá", "uvedmoiť si", "vyliať",
            "prijať", "rozpadnúť sa", "starosť", "tenis", "uviazať", "vyliečiť",
            "príjemný", "rozprávať", "stáť", "tento", "uvoľniť", "vyliečenie",
            "prikázať", "rozprávať sa", "stať sa", "teplý", "uvoľniť sa", "vyliečiť sa",
            "prikryť", "rozsypať", "stav", "terasa", "úzky", "vyliezť",
            "prikrývka", "rozšíriť", "staviť", "termín", "už", "vyložiť",
            "prilepiť", "rozšíriť sa", "sťažeň", "tešiť sa", "v, vo", "vymeniť",
            "príliš", "roztiahnuť", "sťažovať sa", "tiecť", "vak", "vymyslieť",
            "príloha", "roztopiť", "sťažovať", "ticho", "variť", "vymyslieť si",
            "priložiť", "roztopiť sa", "stena", "tisíc", "vás", "vynikajúci",
            "prinútiť", "roztrhnúť", "stĺp", "tlačiť", "váš", "vynoriť sa",
            "prípad", "rozumieť", "sto", "tlačiť sa", "vážiť", "vypiť",
            "pripevniť", "rozviazať", "stojan", "tlak", "vážiť si", "vyplniť",
            "pripojiť", "rôzny", "stolička", "tma", "väzenie", "vypnúť",
            "pripojiť sa", "ručný", "stiahnuť", "tmavý", "včas", "vypovedať",
            "prispieť", "rukavica", "stiahnuť sa", "točiť", "vec", "výprava",
            "prísť", "rukojemník", "stlačiť", "točiť sa", "večer", "vyprázdniť",
            "pristáť", "rušiť", "stlmiť", "topiť", "večera", "vypustiť",
            "pristátie", "ružový", "stolný", "topiť sa", "večerať", "vyriešiť",
            "prístroj", "ryba", "stopa", "tovar", "vedenie", "vyrovnať",
            "prístupný", "rýchlik", "stopovať", "trafiť", "vedieť", "vyrovnať sa",
            "pritiahnuť", "s, so", "stornovať", "tragédia", "vedúci", "vysávač",
            "prítomný", "sadnúť", "strana", "traktor", "veľa", "vysávať",
            "príves", "sadzba", "strašný", "trasa", "veľký", "vyskočiť",
            "prízemie", "sám", "stratiť", "trať", "veľmi", "vyskúšať",
            "príznak", "samozrejme", "stratiť sa", "tráva", "veľvyslanec", "výsledok",
            "priznať", "sankcia", "strava", "tráviť", "veľvyslanectvo", "výsluch",
            "priznať sa", "sebe", "stred", "trest", "ventilátor", "vysoký",
            "prosiť", "sem", "stredisko", "trezor", "veriť", "vysťahovať sa",
            "proti", "servis", "stredný", "trhať", "vesta", "výstava",
            "prst", "sestra", "stretnúť", "trieda", "vhodný", "vystrašiť",
            "prsteň", "sezóna", "stretnúť sa", "trochu", "vchod", "vystreliť",
            "pršať", "schod", "striedať", "trvať", "Vianoce", "vystriedať",
            "prúd", "schopný", "striekačka", "tu", "vidiek", "výstroj",
            "prudký", "schránka", "strieľať", "tvrdý", "vidieť", "vystúpiť",
            "pruh", "schváliť", "stroj", "turista", "vidieť sa", "vysvetliť",
            "prút", "siahnuť", "strom", "tvár", "viesť", "vysvetliť sa",
            "prvý", "sieť", "stroskotať", "tvoj", "vila", "vyšetriť",
            "pstruh", "signál", "studený", "tvoja", "vjazd", "zoznam",
            "pulóver", "silný", "stúpať", "tvrdiť", "vlámanie", "zoznámiť sa",
            "pult", "situácia", "súčasne", "tvrdý", "vlas", "zranený",
            "pustiť", "skákať", "súhlasiť", "tyč", "vlastniť", "zraziť",
            "pustiť sa", "skala", "súprava", "týkať sa", "vlastný", "zraziť sa",
            "puška", "skočiť", "súrny", "typ", "vlek", "zrážka",
            "púšť", "skomplikovať", "surový", "ublížiť", "vliecť", "zrelý",
            "púť", "skomplikovať sa", "susedný", "ubytovať sa", "vlna", "zrušiť",
            "radiť", "skončiť", "súťaž", "učesať", "vnuk", "zrútiť sa",
            "raja", "skoro", "svah", "učesať sa", "vnútrozemie", "zrýchliť",
            "rak", "skôr", "sveter", "učiť", "vodič", "zub",
            "rakva", "skryť", "svetlý", "učiť sa", "vodopád", "zubár",
            "rám", "skryť sa", "sviatok", "učiteľ", "vojsť", "priateľstvo",
            "rampa", "skrývať", "sviečka", "udalosť", "volant", "priateľský",
            "rásť", "skrývať sa", "svietiť", "údolie", "volať", "pulz",
            "rastlina", "skúsiť", "svrbieť", "udrieť", "volať sa", "pútnik",
            "rebrík", "skutočný", "syn", "udržať", "voľný", "putovanie",
            "recepcia", "skutok", "šatka", "uhasiť", "voňať", "opýtať sa",
            "recept", "skvelý", "šatňa", "uhlie", "predtým", "registrovať",
            "reč", "slabý", "šaty", "uistiť", "voziť", "rozbiť sa",
            "regál", "sladký", "šéf", "uistiť sa", "vracať", "rozrušiť",
            "registrácia", "slanina", "šek", "ukázať", "vrátane", "rozrušenie",
            "reklamovať", "slávnosť", "šikovný", "ukončiť", "vrátiť", "sieň",
            "remeň", "sledovať", "široký", "ukradnúť", "vraziť", "skok",
            "republika", "slepý", "šiť", "ukryť", "vreckovka", "stráž",
            "rešpektovať", "slimák", "škatuľa", "uložiť", "vrhnúť sa", "stretnutie",
            "revízor", "slobodný", "škoda", "umrieť", "vrchnák", "striekať",
            "porezať sa", "slovo", "škola", "úmysel", "vrchol", "svetlovlasý",
            "rezať", "slučka", "škriabať", "úmyselne", "vrtuľník", "svetlomet",
            "rezeň", "smer", "zvierať", "uniesť", "vstať", "svetadiel",
            "rezerva", "smotana", "šnúra", "uplatniť", "vstup", "svrbenie",
            "rezervovať", "snažiť sa", "šoférovať", "upevniť", "vtupenka", "šofér",
            "riasa", "snežiť", "šokovať", "úplný", "vstupné", "vyhodiť",
            "rieka", "socha", "španielčina", "upokojiť", "všetci", "výhodný",
            "spomenúť si", "soľnička", "šperk", "upokojiť sa", "všetko", "vydať sa",
            "spôsob", "sopka", "špička", "upozorniť", "všimnúť si", "vydržat",
            "spôsobiť", "spadnúť", "špinavý", "upratať", "vták", "výhľad",
            "správa", "spáliť", "štart", "úrad", "vtip", "vyhnať",
            "takto", "spáliť sa", "študent", "úradník", "vy", "vyhnúť sa",
            "takže", "spať", "štvorec", "úraz", "vybaviť", "usadiť",
            "tam", "späť", "štvorcový", "uraziť", "výborný", "usadiť sa",
            "tamten", "splniť", "štvrť", "uraziť sa", "vybrať", "tak",
            "úschovňa", "spodný", "šumivý", "urážka", "vybuchnúť", "taký",
            "usliovať sa", "spojiť", "táboriť", "určiť", "vyčistiť", "spolu",
            "uskladniť", "spojiť sa", "tabuľa", "určite", "vydanie", "spomenúť",
            "usmiať sa", "spoločný", "ťahať", "urobiť", "vydať",
            "preskúmanie",
            "presný",
            "presnosť",
            "prestieradlo",
            "presunúť",
            "presunúť sa",
            "presun",
            "presvedčiť",
            "presvedčiť sa",
            "pretlmočiť",
            "pretože",
            "prevaha",
            "prevažovať",
            "prevládať",
            "prevrátiť",
            "prevrhnúť sa",
            "prevýšiť",
            "prezliekareň",
            "prezradiť",
            "preškrtnúť",
            "prežiť",
            "prežrieť",
            "prežúvať",
            "pri",
            "pričleniť",
            "pričleniť sa",
            "priľahlý",
            "priľnavý",
            "priľnúť",
            "priťahovať",
            "priať",
            "priať si",
            "priamy",
            "prianie",
            "priateľskosť",
            "pribehnúť",
            "priblížiť",
            "priblížiť sa",
            "pribrať",
            "pribúdať",
            "prichystať",
            "prichýliť",
            "prideliť",
            "pridružiť sa",
            "priebeh",
            "priekopnícky",
            "priekopník",
            "prieliv",
            "prieplav",
            "priepustka",
            "priestranný",
            "prifarbiť",
            "prihodiť sa",
            "prihriať",
            "prijatie",
            "prikročiť",
            "prikývnuť",
            "prilepiť sa",
            "priliehavý",
            "prilipnúť",
            "priložený",
            "primitívny",
            "prinútiť sa",
            "priorita",
            "pripiť",
            "pripisovať",
            "pripodobniť",
            "pripojený",
            "pripomenúť",
            "pripomenúť si",
            "pripomienka",
            "pripravený",
            "pripraviť sa",
            "pripustiť",
            "pripútať",
            "prirodzene",
            "prirodzený",
            "prirovnať",
            "prisľúbiť",
            "prisťahovať sa",
            "prisťahovalecký",
            "prisladiť",
            "prispievať",
            "prispôsobiť",
            "prispôsobiť sa",
            "prisvedčiť",
            "pritakať",
            "pritakanie",
            "priveľmi",
            "priviazať",
            "privilegovať",
            "privinúť",
            "privítať",
            "privítanie",
            "privoliť",
            "príbeh",
            "príboj",
            "príborník",
            "prídavný",
            "príhoda",
            "prímorský",
            "prípitok",
            "prísľub",
            "prísada",
            "prísaha",
            "príslušný",
            "prísny",
            "prístrešok",
            "prítok",
            "prívesok",
            "prívod",
            "prívrženec",
            "procesia",
            "produkovať",
            "profesor",
            "profitovať",
            "programovanie",
            "projektor",
            "projekt ",
            "projektovať",
            "propaganda",
            "propagácia",
            "prospekt",
            "prostý",
            "protijed",
            "protiklad",
            "protirečenie",
            "protirečiť",
            "protirečiť si",
            "protivník",
            "protokol",
            "prototyp",
            "provincia",
            "provokovať",
            "prstenec",
            "íngreme",
            "pružina",
            "pružný",
            "prúdiť",
            "psí",
            "psychiater",
            "psychiatria",
            "psychológ",
            "publikácia",
            "publikovať",
            "publikum",
            "puding",
            "pukance",
            "puklina",
            "punč",
            "purpurový",
            "pustatina",
            "pustovník",
            "pustý",
            "puto",
            "puk",
            "pykať",
            "pyramída",
            "pyšný",
            "pýcha",
            "pýšiť sa",
            "pšenica",
            "rabín",
            "rada",
            "radar",
            "radca",
            "radiátor",
            "radikál",
            "radovať sa",
            "radšej",
            "ragby",
            "rajčina",
            "raketa",
            "Rakúsko",
            "rameno",
            "ramienko",
            "raniť",
            "rasa",
            "rast",
            "rastlinný",
            "ražeň",
            "rátať",
            "realizovať",
            "realizovať sa",
            "recesia",
            "recitovať",
            "recyklovať",
            "redigovať",
            "redukcia",
            "referovať",
            "reflektor",
            "reformátor",
            "regenerácia",
            "regulovať",
            "rehoľa",
            "relaxovať",
            "rely",
            "remizovať",
            "renovovať",
            "reportér",
            "reprezentant",
            "reprezentácia",
            "reprezentovanie",
            "reprodukovať",
            "reproduktor",
            "reputácia",
            "resumé",
            "retiazka",
            "reuma",
            "rev",
            "revať",
            "revolta",
            "revue",
            "rez",
            "rezák",
            "rezký",
            "reštaurovať",
            "režisér",
            "režírovať",
            "riť",
            "riadiť",
            "riaditeľ",
            "riaditeľstvo",
            "riadok",
            "riečka",
            "riediť",
            "riedky",
            "ring",
            "riskovať",
            "rival",
            "rivalita",
            "ríbezľa",
            "roľa",
            "rod",
            "rodiť",
            "rodisko",
            "rodný",
            "rohožka",
            "roklina",
            "rokovať",
            "rokovanie",
            "ropa",
            "ropný",
            "ropucha",
            "rotunda",
            "rovnako",
            "rovnobežka",
            "rovnobežný",
            "rovnováha",
            "rozčarovať",
            "rozčleniť",
            "rozčúliť",
            "rozčúliť sa",
            "rozbaliť",
            "rozdať",
            "rozdeľovač",
            "rozdrobiť",
            "rozdrviť",
            "rozhnevať",
            "rozhnevať sa",
            "rozhodca",
            "rozhodnúť",
            "rozhodnúť sa",
            "rozhodný",
            "rozhorčiť sa",
            "rozhorčenie",
            "rozhovor",
            "rozhrýzť",
            "rozísť sa",
            "rozkaz",
            "rozkázať",
            "rozklad",
            "rozkladať sa",
            "rozlíšiť",
            "rozloha",
            "rozluka",
            "rozlúčenie",
            "rozlúčka",
            "rozmaznávať",
            "rozmeniť",
            "rozmliaždiť",
            "rozmnožiť",
            "rozmnožovať",
            "rozmnožovať sa",
            "rozmnožovanie",
            "rozmýšľať",
            "roznášať",
            "rozniesť",
            "rozniesť sa",
            "rozoznať",
            "rozpŕchnuť sa",
            "rozpad",
            "rozpínať sa",
            "rozplynúť sa",
            "rozpor",
            "rozpoznať",
            "rozprávač",
            "rozprávanie",
            "rozprestierať sa",
            "rozpestrieť",
            "rozptýliť",
            "rozptýliť sa",
            "rozpustiť",
            "rozpustiť sa",
            "rozsah",
            "rozsiahly",
            "rozsudok",
            "rozsypať",
            "roztaviť",
            "roztaviť sa",
            "roztrúsiť",
            "roztvoriť",
            "rozum",
            "rozveseliť",
            "rozvidnievať sa",
            "rozviesť sa",
            "rozvinúť",
            "rozvinúť sa",
            "rozvíjať",
            "rozvíjať sa",
            "rozzúriť",
            "rozzúriť sa",
            "rozšíriť",
            "roštenka",
            "röntgenogram",
            "ručička",
            "ruch",
            "rukopis",
            "rukoväť",
            "Rumunsko",
            "rušný",
            "ryť",
            "rypák",
            "rysovať",
            "rytec",
            "rytier",
            "rytina",
            "sčítať",
            "sčítaný",
            "sľúbiť",
            "sťahovanie",
            "sťažiť",
            "sať",
            "sad",
            "sadenie",
            "sadlo",
            "safari",
            "sakristia",
            "salón",
            "salsa",
            "salto",
            "samba",
            "samec",
            "samoľúby",
            "samohláska",
            "samostatnosť",
            "samotár",
            "samotársky",
            "samotný",
            "sanatórium",
            "saxofón",
            "scediť",
            "scenár",
            "scenárista",
            "scéna",
            "scénograf",
            "schéma",
            "schizofrénia",
            "schnúť",
            "schopnosť",
            "schovať",
            "absolvovať", "adresa", "advokát", "ahoj", "aj", "ak ", "ako", "aký", "alebo", "ambasáda",
            "antický", "antikoncepcia", "asi", "auto", "babka", "balón", "banka", "bankovka", "baňa", "bahno,baliť", "balón", "baran",
            "báť sa", "batožina", "baviť sa", "baviť", "bazén", "bezvedomie", "bežať", "bežný", "bielizeň", "biely", "biftek", "biť sa",
            "bitka", "blato", "blázon", "bledý", "blesk", "blízky", "blokovať", "blúzka", "bodnúť", "boh", "bojovať", "bok", "bolest",
            "bolestný", "brada", "brána", "brániť", "brániť sa", "brať", "breh", "brucho", "brzdiť", "bufet", "búchať ", "búrka", "bydlisko",
            "byt", "byť", "bývalý", "celkom", "	cenný", "centrum", "cesta", "cestovať", "cez", "cibuľa", "cieľ", "cítiť", "cítiť sa",
            "čudný", "cudzinec", "cukrík", "cukrovka", "cúvať", "cúvnuť", "cvičiť", "cisterna", "citovať", "cválať", "cvičenie", "cyklista",
            "cyklus", "čaj", "čakan", "časť", "často", "častý", "čašník", "černoch", "červený", "čiara", "čistý", "čižma", "člen", "čln",
            "čo", "čokoláda", "čudovať sa", "Čech", "čajka", "ďalej", "ďaleko", "ďaleký", "ďalší", "dar", "dátum", "dávno", "dedko", "defekt",
            "dejiny", "deka", "deliť", "deliť sa", "denne", "detail", "deväť", "deväťdesiat", "deväťsto", "diaľnica", "dieťa", "diskusia",
            "diskutovať", "divák", "divoký", "dlhovať", "dno", "do", "doba", "dobre", "dobrý", "dodatočný", "dodržať", "dodržiavať", "dohoda",
            "dohodnúť sa", "dokázať", "dokončiť", "dole", "dom", "domáci", "domorodec", "domov", "donútiť", "dopĺňať", "dopoludnie", "doprava",
            "dopredu", "doručiť", "doska", "dostať", "dostať sa", "dostihnúť", "dotknúť sa", "dovidenia", "doviezť", "dovoliť", "dozadu",
            "dozor", "dôjsť", "dôverný", "dôvod", "dráha", "drahý", "drobné", "drôt", "drsný", "druh", "drzý", "držadlo", "držať", "držať sa",
            "dúfať", "dusiť sa", "dva", "dvadsať", "dvanásť", "dýchať", "džús", "ekonómia", "električka", "elektrický", "energia", "Európan",
            "európsky", "existovať", "falošný", "farba", "filé", "firma", "fľak", "fúkať", "fungovať", "gól", "golier", "gombík", "guľa",
            "guma", "had", "hádať sa", "hanbiť sa", "handra", "havária", "helikoptéra", "hľadať", "hladký", "hladný", "hlava", "hlavne",
            "hlavný", "hlboký", "hliadka", "hluk", "hneď", "hnevať sa", "hnevať", "hniezdo", "hoci", "hodina", "hodiť", "hodiť sa", "hojdať sa",
            "holiť", "holiť sa", "holý", "horčica", "hore", "horieť", "horký", "horúci", "horúčava", "hosť", "hostiteľ", "hotový", "hovno",
            "hovor", "hovoriť", "hra", "hračka", "hrach", "hrať", "hrať sa", "hrebeň", "hrob", "hrubý", "huba", "hudobný", "humor", "husle",
            "hustý", "hviezda", "hýbať", "hýbať sa", "chalupa", "chaos", "chcieť", "chlap", "chlp", "chodba", "chodec", "chodiť", "chodník",
            "choroba", "chovať", "chrbát", "chrípka", "chudák", "chudý", "chutiť", "chváliť", "chváliť sa", "chvíľa", "chvost", "chyba",
            "chýbať", "chytať", "chytiť", "iba", "ihrisko", "infarkt", "infekcia", "informovať", "injekcia", "iný", "inzerát", "ísť", "iste",
            "istý", "izolovať", "ja", "jama", "jasný", "jazdiť", "jazero", "jedenásť", "jediný", "jedlo", "jeho", "jej", "jesť", "k", "kabelka",
            "kačica", "kaňon", "kapusta", "karta", "kašlať", "káva", "kaviareň", "keby", "keď", "kedysi", "kel", "kempovať", "kilogram", "kino",
            "kladivo", "klavír", "kĺb", "klenotníctvo", "klinec", "klobása", "klobúk", "klopať", "klub", "kľučka", "kohútik", "koláč", "koleso",
            "koľko", "kolo", "komár", "kompletný", "komplikovaný", "komunikácia", "konár", "konať", "koncert", "kondóm", "konečne", "kontakt",
            "konzerva", "kopať", "kópia", "korčuľa", "korčuľovať sa", "koruna", "košeľa", "kov", "krab", "krádež", "kraj", "krajina", "krásny",
            "krém", "kresliť", "kreveta", "krok", "kruh", "krúpa", "krvácať", "kto", "ktorý", "ktorýkoľvek", "kufor", "kuchyňa", "kapele",
            "kúpiť", "kurz", "kým", "kyselina", "kyslý", "lampa", "lano", "látka", "len", "lep", "lepší", "let", "letieť", "ležať", "liezť",
            "línia", "linka", "list", "lístok", "liter", "lokomotíva", "lopta", "loviť", "ľudový", "lúpež", "ľutovať", "lyžica", "majetok",
            "majiteľ", "majonéza", "maľovať", "mandarínka", "masť", "mäkký", "mäso", "mäta", "medzitým", "menej", "mesiac", "mesto", "meter",
            "schudobnieť",
            "schvaľovať",
            "presiahnuť",
            "sebec",
            "sebecký",
            "sedatívum",
            "sedlo",
            "sedmokráska",
            "sekať",
            "sekcia",
            "sekretárka",
            "sekt",
            "sekundárny",
            "semenník",
            "semeno",
            "seminár",
            "sen",
            "senior",
            "serenáda",
            "seriózny",
            "severovýchodný",
            "servírovať",
            "Severoameričan",
            "severoamerický",
            "severozápad",
            "severozápadný",
            "sféra",
            "sformovať",
            "sformovaný",
            "siať",
            "sila",
            "simulovať",
            "sirota",
            "situovať",
            "sídliť",
            "sídliaci",
            "skladať",
            "skladateľ",
            "sklamať",
            "sklamanie",
            "skloniť sa",
            "skláňať sa",
            "skomponovať",
            "skorumpovaný",
            "skrachovať",
            "skrátiť",
            "skrášliť",
            "skriviť",
            "skrkvať",
            "skrotiť",
            "skrotnúť",
            "skrýša",
            "skutočne",
            "skutočnosť",
            "skúmať",
            "skúška",
            "skysnúť",
            "slabosť",
            "sladkosť",
            "slama",
            "sláčik",
            "sláva",
            "sláviť",
            "slávka",
            "sled",
            "slepec",
            "slezina",
            "slintať",
            "sloh",
            "slonovina",
            "Slovensko",
            "Slovinsko",
            "sluch",
            "slušný",
            "slúžiť",
            "smažiť",
            "smieť",
            "smiešny",
            "smrečina",
            "smrteľný",
            "snaha",
            "sob",
            "sochárstvo",
            "sociológia",
            "sociológ ",
            "sólo",
            "spariť",
            "spáchať",
            "sperma",
            "spev",
            "spievať",
            "spisovateľ",
            "splachovač",
            "splodiť",
            "spojenectvo",
            "spojenie",
            "spoločník",
            "spoluhláska",
            "spolunažívať",
            "spolupracovať",
            "spolužiak",
            "spomienka",
            "spor",
            "sporiť",
            "spotiť sa",
            "spotrebovať",
            "spoznať",
            "spozorovať",
            "spravodlivo",
            "spravodlivý",
            "spráchnivieť",
            "správanie",
            "správne",
            "sprevádzať",
            "sprostý",
            "sprostosť",
            "Srb",
            "Srbsko",
            "srbčina",
            "srbský",
            "srvátka",
            "stagnovať",
            "stan",
            "stanovať",
            "stanoviť",
            "starať sa",
            "starec",
            "starnúť",
            "starobylý",
            "starostlivosť",
            "staroveký",
            "stavať",
            "stavba",
            "stavebníctvo",
            "stále",
            "stenať",
            "sterlizácia",
            "sterlizovať",
            "sterilnosť",
            "stimulovať",
            "stisnúť",
            "stíchnuť",
            "stlačený",
            "stmavnúť",
            "stmievať sa",
            "stmievanie",
            "stojan",
            "stonať",
            "stopky",
            "stotina",
            "strata",
            "stráviť",
            "strela",
            "strelec",
            "streliť",
            "strihať",
            "stroskotanec",
            "stroskotanie",
            "stručný",
            "struna",
            "strúhať",
            "stučnieť",
            "stuchlina",
            "stuha",
            "stupnica",
            "stvoriť",
            "suka",
            "surfovať",
            "sušiť",
            "súčasný",
            "súťažiť",
            "súcit",
            "súhlas",
            "súmrak",
            "súper",
            "súperenie",
            "súperiť",
            "sústrediť",
            "sústrediť sa",
            "súvislosť",
            "svedčiť",
            "sviňa",
            "svieži",
            "svitať",
            "svitanie",
            "svokra",
            "symbol",
            "sympatia",
            "sympatizovať"};

*/

/*
    private static String[] words = {"metro",
            "miestny",
            "miesto",
            "miešať",
            "milión",
            "milionár",
            "milionársky",
            "milý",
            "minimálny",
            "minúť",
            "minúť sa",
            "minúta",
            "misa",
            "miska",
            "mladík",
            "mladý",
            "móda",
            "moderný",
            "modrina",
            "moriak",
            "motor",
            "motorka",
            "motýľ",
            "môcť",
            "moja",
            "môj",
            "mrazenie",
            "mrazivý",
            "mŕtvy",
            "múdry",
            "mucha",
            "mudrc",
            "múr",
            "musieť",
            "mušľa",
            "muzikál",
            "my",
            "mydliť",
            "myslieť",
            "myslieť si",
            "mýto",
            "mys",
            "mykóza",
            "mužstvo",
            "mužský",
            "mužný",
            "murár",
            "mulat",
            "mučiť",
            "mrmlať",
            "mrieť",
            "mrholiť",
            "mrhať",
            "mravec",
            "mramor",
            "mozog",
            "mozaika",
            "motocyklista",
            "motocykel",
            "motivovať",
            "moslimský",
            "moslim",
            "moruša",
            "morfium",
            "montovať",
            "monológ",
            "monitor",
            "Mongol",
            "mongolský",
            "mongolčina",
            "momentka",
            "mohamedánstvo",
            "modlitba",
            "modliť sa",
            "modla",
            "modifikovať",
            "moderátor",
            "model",
            "mocný",
            "mocnosť",
            "moc",
            "močiť",
            "moč",
            "množina",
            "mnoho",
            "mníška",
            "mních",
            "mlieť",
            "mlátiť",
            "mláďa",
            "mína",
            "mixér",
            "misionár",
            "milimeter",
            "mikrovlnná rúra",
            "mikroorganizmus",
            "mikrofón",
            "mihalnica",
            "migréna",
            "miešanec",
            "miestnosť",
            "miesiť",
            "mierumilovný",
            "mierny",
            "mierka",
            "miera",
            "mienka",
            "mieniť",
            "méta",
            "mešťan",
            "mexický",
            "Mexičan",
            "na",
            "nadbytok",
            "nádcha",
            "nadjazd",
            "nadmerný",
            "nádrž",
            "nahnevať",
            "nahnevať sa",
            "náhodou",
            "náhradný",
            "nahý",
            "nahota",
            "nachádzať sa",
            "nainštalovať",
            "najmä",
            "nájomné",
            "nájomník",
            "najprv",
            "najskôr",
            "nájsť",
            "nakaziť",
            "nakoniec",
            "nalepiť",
            "naliať",
            "nalodiť sa",
            "naložiť",
            "námestie",
            "námietka",
            "namočiť",
            "namontovať",
            "námorník",
            "námornícky",
            "naopak",
            "naozaj",
            "napadnúť",
            "napätie",
            "napísať",
            "naplánovať",
            "napnúť",
            "náprava",
            "napraviť",
            "napriek",
            "náradie",
            "naraz",
            "naraziť",
            "náročný",
            "nárok",
            "nasledovať",
            "nastaviť",
            "nástupište",
            "nastúpiť",
            "náš",
            "natiahnuť",
            "natrieť",
            "naučiť sa",
            "náušnica",
            "navigácia",
            "navrhnúť",
            "navštíviť",
            "názor",
            "nedeľa",
            "nedostatok",
            "nehoda",
            "nechať",
            "nenávisť",
            "nenávidieť",
            "nepríjemný",
            "neskoro",
            "nesúhlas",
            "nešťastie",
            "nevesta",
            "nezmysel",
            "neznášať",
            "nič",
            "niečo",
            "niesť",
            "nijaký",
            "nízky",
            "noha",
            "nohavice",
            "nohavičky",
            "nos",
            "nosič",
            "nosiť",
            "november",
            "noviny",
            "nový",
            "nútiť",
            "ňufák",
            "naberačka",
            "nabiť",
            "nacionalizmus",
            "nadanie",
            "nadchnúť",
            "nadchnúť sa",
            "nadobudnúť",
            "nadriadený",
            "o",
            "obec",
            "obaja",
            "obilie",
            "obísť",
            "objaviť",
            "objaviť sa",
            "objednať",
            "objem",
            "oblečenie",
            "oblek",
            "obliecť sa",
            "obmedzený",
            "obrátiť",
            "obrátiť sa",
            "obsadiť",
            "obsahovať",
            "obťažovať",
            "obuv",
            "obväz",
            "obviňovať",
            "obviniť",
            "obyčajný",
            "očakávať",
            "od",
            "odbaviť",
            "odbočiť",
            "oddelenie",
            "odev",
            "odfotografovať",
            "odhadnúť",
            "odísť",
            "odkaz",
            "odložiť",
            "odoslať",
            "odovzdať",
            "odpadnúť",
            "odpočívať",
            "oddychovať",
            "odpojiť",
            "odporučiť",
            "odstrániť",
            "odltlačok",
            "odtrhnúť",
            "odvážny",
            "odviazať",
            "odviesť",
            "oficiálny",
            "ohlásiť",
            "ohnisko",
            "ohnúť",
            "oholiť sa",
            "oholiť",
            "ohrada",
            "ochranný",
            "okradnúť",
            "okrem",
            "okruh",
            "olovo",
            "ošúpať",
            "omeleta",
            "omyl",
            "oneskoriť sa",
            "opakovať",
            "opasok",
            "operácia",
            "opica",
            "opísať",
            "opitý",
            "opraviť",
            "oprávnenie",
            "oprieť",
            "oprieť sa",
            "optika",
            "opuchnúť",
            "oranžový",
            "ordinácia",
            "organizovať",
            "originál",
            "osem",
            "osemdesiat",
            "ospravedlniť sa",
            "ostrý",
            "osvedčenie",
            "otočiť",
            "otočiť sa",
            "otráviť",
            "otvor",
            "otvorený",
            "otvoriť",
            "ovplyvniť",
            "označiť",
            "oznámenie",
            "oznámiť",
            "páčiť sa",
            "padnúť",
            "palác",
            "palica",
            "páliť",
            "palma",
            "pamäť",
            "pamätať si",
            "pamiatka",
            "panvica",
            "paprika",
            "pár",
            "parkovať",
            "párok",
            "partner",
            "pás",
            "patriť",
            "pauza",
            "päta",
            "päťdesiat",
            "pečiatka",
            "pedál",
            "pekný",
            "peňaženka",
            "peniaze",
            "pero",
            "pes",
            "pestrý",
            "pevnosť",
            "pevný",
            "piecť",
            "pichnúť",
            "pilník",
            "pilot",
            "písať",
            "pískať",
            "písmeno",
            "piť",
            "pivnica",
            "plachta",
            "plakať",
            "platiť",
            "plátok",
            "plavba",
            "plavčík",
            "pláž",
            "plece",
            "plech",
            "pleseň",
            "plod",
            "plochý",
            "plot",
            "pľúca",
            "plutva",
            "počuť",
            "pod",
            "podariť sa",
            "podať",
            "podceniť",
            "pódium",
            "podľa",
            "podlaha",
            "podnik",
            "podobať sa",
            "podpáliť",
            "podporiť",
            "podporovať",
            "podradný",
            "podrobnosť",
            "podstata",
            "podvod",
            "podvodník",
            "pohár",
            "pohnúť sa",
            "pohorie",
            "pohotovosť",
            "pohrýzť",
            "pochopiť",
            "pochváliť",
            "pokazený"};
*/

/*
    private static String[] words = {"chvieť sa", "chytrák", "cieva", "cirkulovať", "cisársky", "citovať", "citrónovník", "civilista", "civilný", "cícer", "cín", "cíp",
            "ctiteľ", "cudnosť", "cudzí", "cukornička", "cukrový", "cvičiteľ", "čarovný", "časomer", "červotoč", "česať", "česať sa", "čiastočne", "čipka", "číhať", "číry",
            "článok", "čokoládový", "črevo", "čulý", "ďakovať", "ďumbier", "ľahostajný", "ľakať", "ľan", "ľúbezný", "ľútosť", "dabovať", "darebák", "darebný", "datľa", "dav",
            "dáma", "dážďovka", "debata", "debatovať", "debil", "debna", "decentnosť", "dedič", "dedičstvo", "dedina", "dedinský", "dedukovať", "definitívne", "definovať",
            "deformácia", "deformovať", "degenerovať", "degradovať", "degustovať", "dehydrovať", "dekáda", "deklarácia", "deklarovať", "dekoratívny", "dekorácia", "delegát",
            "delírium", "delta", "demižón", "denník", "deportovať", "depozit", "depresia", "derivovať", "dermatitída", "dermatológ", "desaťročie", "desiť", "detektívka",
            "detektívny", "dezinfikovať", "dezorientovať", "dielo", "dielňa", "diktátor", "diplomat", "dirigent", "disciplína", "disk", "disponovať", "distribučný",
            "distribútor", "diviť sa", "dlaň", "dlážka", "dláždený", "dobyť", "dodať", "dojať", "dojka", "dokazovať", "dokonale", "dolina", "dolný", "domestikovať",
            "dominovať", "domnievať sa", "domýšľavý", "dopisovateľ", "doplnok", "dosiahnuť", "doslov", "dostaviť sa", "dotyk", "dovážať", "dôvera", "dráždiť", "driek",
            "egoista", "ekzém", "elastický", "električenka", "eliminovať", "emigrovať", "esej", "estetika", "eukalyptus", "exkurzia", "expandovať", "expedícia", "exportovať",
            "farár", "farbiť", "falšovať", "farebný", "farma", "fascinovať", "fialka", "figúra", "fikcia", "flauta", "fond", "forma", "formálny", "fóbia", "frak", "frekvencia",
            "freska", "fúzy", "fyzik", "fyzika", "fyzioterapia", "galoša", "gangster", "garantovať", "gaštan", "gaštanový", "genetika", "geometria", "gestikulovať", "golf",
            "gratulovať", "guľatý", "gymnasta", "hala", "hanba", "hašiš", "hádka", "hádzať", "hodnotiť", "hormón", "horolezec", "horolezectvo", "hospitalizovať", "hospodárstvo",
            "hostina", "hovorca", "hrada", "hrb", "hrboľatý", "hrdosť", "hrdý", "hrmieť", "hromada", "hromadiť", "hromadný", "hroziť", "hrozienko", "hrýzť", "humánny", "hundrať",
            "huslista", "hutníctvo", "húsenica", "hvízdať", "hydratačný", "hydratovať", "hysterik", "hysterický", "hystéria", "identifikácia", "identifikovať", "idiot", "idol",
            "ignorovať", "ilustrácia", "ilustrovať", "indivíduum", "informatika", "ingrediencia", "inklinovať", "integrovať", "inteligencia", "intenzívny", "interiér", "exteriér",
            "interprét", "interupcia", "intervenovať", "intoxikácia", "intoxikovať", "intrigovať", "investovať", "inzerovať", "inšpirovať", "inštalovať", "inštruktor", "istiť",
            "istota", "Ír", "írsky", "jachta", "jadro", "jagavý", "jarabica", "jedinečný", "jednotný", "jeleň", "joga", "kŕč", "kamarátstvo", "kandidát", "kapela", "kapitál",
            "kapitola", "karamel", "karate", "kardiológ", "klamstvo", "klas", "klasický", "klesať", "klesnúť", "klinček", "lákať", "lámať", "lámať sa", "lenivý", "leták", "lietať",
            "leštiť", "lichotiť", "liečba", "liečiť", "limonáda", "lov", "luxus", "mŕtvy", "majstrovstvá", "maloletý", "marihuana", "maska", "maskovať", "meč", "mechanický",
            "mechanik", "mechúr", "medaila", "medicína", "mierumilovný", "mierny", "minister", "mlátiť", "mlieť", "močiť", "moderný", "modifikovať", "môcť", "mrholiť", "mučiť",
            "musieť", "múdry", "myslieť", "myslieť si"
    };

*/

/*
    private static String[] words = {"vyšetrovanie",
            "výťah",
            "vytiahnuť",
            "vytlačiť",
            "vytrhnúť",
            "využiť",
            "vývar",
            "vyvážať",
            "vyviezť",
            "vyvíjať",
            "vyvinúť",
            "vyvrátiť",
            "vyzliecť",
            "vyzliecť sa",
            "vyznať sa",
            "vyžadovať",
            "vzadu",
            "vzdať sa",
            "vzdialenosť",
            "vziať",
            "vziať si",
            "z",
            "za",
            "zabaliť",
            "zabezpečiť",
            "zabiť",
            "zablokovať",
            "zabrať",
            "zabrzdiť",
            "začať",
            "začiatočník",
            "zadný",
            "zadok",
            "zadržať",
            "zadusiť",
            "zadusiť sa",
            "zafarbiť",
            "zahraničný",
            "záchod",
            "zachovať",
            "zachrániť",
            "záchvat",
            "zájazd",
            "základ",
            "základný",
            "zaklopať",
            "zakotviť",
            "zákruta",
            "zakryť",
            "záloha",
            "zamieriť",
            "zámok",
            "zapáliť",
            "zapamätať si",
            "zaparkovať",
            "zápas",
            "zápcha",
            "zapísať",
            "zapísať sa",
            "zaplatiť",
            "zaplaviť",
            "zapnúť",
            "zapojiť sa",
            "zaregistrovať",
            "zaregistrovať sa",
            "zariadiť",
            "zároveň",
            "záruka",
            "zase",
            "zasiahnuť",
            "zaslúžiť si",
            "zastaviť",
            "zástrčka",
            "zástupca",
            "zásuvka",
            "zašiť",
            "zašpiniť",
            "zatelefonovať",
            "zatiahnuť",
            "zatiaľ",
            "zatknúť",
            "zatvoriť",
            "zatvoriť sa",
            "zaútočiť",
            "záväzný",
            "zavesiť",
            "zaviazať",
            "zaviazať sa",
            "zaviesť",
            "zaviniť",
            "závisieť",
            "závislý",
            "závod",
            "zavolať",
            "zavrieť",
            "zazvoniť",
            "zažiť",
            "zbadať",
            "zbierať",
            "zdať sa",
            "zdravý",
            "zdražieť",
            "zdržať",
            "zdržať sa",
            "zdvihnúť",
            "zdvihnúť sa",
            "zeler",
            "zem",
            "zemiak",
            "zhasnúť",
            "zhodiť",
            "zhoršiť",
            "zhoršiť sa",
            "zhoršovať",
            "zhrnúť",
            "získať",
            "zísť",
            "zísť sa",
            "zistiť",
            "zločin",
            "zlodej",
            "zlomiť",
            "zložiť",
            "zložitý",
            "zlyhať",
            "zmazať",
            "zmätok",
            "zmeniť",
            "zmeniť sa",
            "zmenšiť",
            "zmes",
            "zmiešať",
            "zmiznúť",
            "zmluva",
            "zmrznúť",
            "značka",
            "známka",
            "známy",
            "znásilnenie",
            "znásilniť",
            "znášať",
            "znečistiť",
            "zneužiť",
            "zneužívať",
            "zničiť",
            "zniesť",
            "znížiť",
            "znova",
            "zobrať",
            "zobudiť",
            "zobudiť sa",
            "zodvihnúť",
            "zodvihnúť sa",
            "zohriať",
            "zomrieť",
            "zopakovať",
            "zosilniť",
            "zúčastniť sa",
            "zúčastňovať sa",
            "zúžiť",
            "zúžiť sa",
            "zvaliť",
            "zväčšiť",
            "zverejniť",
            "zveriť",
            "zveriť sa",
            "zviazať",
            "zviera",
            "zvládnuť",
            "zvlášť",
            "zvláštny",
            "zvoniť",
            "zvoniť",
            "zvýšiť",
            "zvyšok",
            "žalúdok",
            "že",
            "želať",
            "želať si",
            "žiadať",
            "žiadosť",
            "žiarovka",
            "žiť",
            "žralok"};
*/

/*
"tabletka",
            "tábor",
            "tácka",
            "talent",
            "tampón",
            "tanec",
            "tank",
            "tapeta",
            "taviť",
            "tehla",
            "telesný",
            "telocvik",
            "temný",
            "tempo",
            "tenista",
            "tepna",
            "terapia",
            "terč",
            "terorizovať",
            "tesať",
            "tesnenie",
            "tesný",
            "testovať",
            "tielko",
            "tichý",
            "tím",
            "Timor",
            "Timorčan",
            "timorský",
            "tisícina",
            "tisícka",
            "tisícročie",
            "tíšiť",
            "tkanina",
            "tkanivo",
            "tkať",
            "tlačiareň",
            "tlieskať",
            "tlmiť",
            "tlmočiť",
            "tok",
            "tolerovať",
            "toľko",
            "tón",
            "tonelada",
            "torta",
            "tradičný",
            "traky",
            "trám",
            "transformovať",
            "transfúzia",
            "transplantácia",
            "trápenie",
            "trápiť",
            "trápiť sa",
            "trblietať sa",
            "trblietavý",
            "tréner",
            "trestať",
            "trestný",
            "triasť",
            "triasť sa",
            "triaška",
            "tristo",
            "tŕň",
            "trojuholník",
            "trstina",
            "trúbka",
            "truhla",
            "truhlica",
            "trup",
            "tržba",
            "tuberkulóza",
            "tučniak",
            "tuhý",
            "turecký",
            "turečtina",
            "Turek",
            "turnaj",
            "tušiť",
            "túžba",
            "túžiť",
            "tvar",
            "tvor",
            "tvorca",
            "tvoriť",
            "tvrdenie",
            "tykadlo",
            "tymián",
            "tyran",
            "týždenník",
            "ubezpečiť",
            "ubližovať",
            "úbohý",
            "úcta",
            "uctiť",
            "uctiť si",
            "účasť",
            "účel",
            "učenie",
            "účtovník",
            "udanie",
            "udať",
            "udeliť",
            "údiť",
            "udobriť",
            "udobriť sa",
            "udusiť",
            "udusiť sa",
            "ukazovať",
            "uľahčiť",
            "uľaviť",
            "ulita",
            "úloha",
            "umenie",
            "umiestniť",
            "umiestňovať",
            "umlčať",
            "umývať",
            "únava",
            "unaviť",
            "unaviť sa",
            "unavovať",
            "uniforma",
            "únik",
            "univerzita",
            "úplatok",
            "úplne",
            "upokojovať",
            "upozornenie",
            "upozorniť",
            "upraviť",
            "uprednostniť",
            "uprednostňovať",
            "úprimne",
            "úprimný",
            "určitý",
            "urýchliť",
            "urýchľovať",
            "usadenina",
            "uschnúť",
            "uskutočniť",
            "uskutočniť sa",
            "uskutočňovať",
            "úsmev",
            "usmievať sa",
            "uspať",
            "uspokojiť sa",
            "ústie",
            "ústny",
            "ustrica",
            "ustúpiť",
            "utečenec",
            "utekať",
            "utešiť",
            "utierať",
            "utíšiť",
            "útok",
            "utrieť",
            "uvažovať",
            "uväzniť",
            "uverejniť",
            "uveriť",
            "uviesť",
            "úvod",
            "uzavrieť",
            "užívať si",
            "vaječník",
            "vakcína",
            "vápno",
            "varovanie",
            "varovať",
            "vášeň",
            "vavrín",
            "väzeň",
            "vďačnosť",
            "vďačný",
            "vdýchnuť",
            "večierok",
            "veda",
            "vedec",
            "vedľajší",
            "vedomosť",
            "veľkosť",
            "veko",
            "veliteľ",
            "veniec",
            "venovať",
            "venovať sa",
            "verejnosť",
            "vernosť",
            "vertikálny",
            "verš",
            "veslo",
            "vešať",
            "video",
            "vidiecky",
            "viečko",
            "vietnamčina",
            "Vietnamec",
            "vietnamský",
            "vinič",
            "viniť",
            "vinica",
            "viola",
            "violončelo",
            "víťaziť",
            "víťazstvo",
            "vírus",
            "vlajka",
            "vložiť",
            "vnútorný",
            "vnútro",
            "vodca",
            "vodný",
            "vodorovný",
            "volejbal",
            "voliť",
            "vonkajší",
            "vonkajšok",
            "voš",
            "vôl",
            "vpredu",
            "vražda",
            "vraždiť",
            "vrchný",
            "vrhnúť",
            "vrhať",
            "vrkoč",
            "vstúpiť",
            "vulgárny",
            "vyčerpať",
            "vyčerpanie",
            "vychladiť",
            "vychladnúť",
            "vychovať",
            "vychovávať",
            "vydra",
            "vydýchnuť",
            "vyhlásenie",
            "vyhlásiť",
            "vyhovieť",
            "vyhovovať",
            "vyjadriť",
            "vyjadriť sa",
            "vyjednávať",
            "vykríknuť",
            "vylepšiť",
            "vylepšenie",
            "vylúčiť",
            "vymazať",
            "vymedziť",
            "vymenovať",
            "vynájsť",
            "vynechať",
            "vyplývať",
            "vyradiť",
            "vyrásť",
            "vyrážka",
            "vyrobiť",
            "vysielať",
            "vyslobodiť",
            "vysokoškolský",
            "vystačiť",
            "vystrihnúť",
            "vysvetlenie",
            "vytvoriť",
            "vyučovať",
            "vyvolať",
            "vyzbrojiť",
            "vyzdobiť",
            "vyzuť",
            "vyzúvať",
            "vyšívať",
            "vyšší",
            "výchova",
            "výchovný",
            "výhoda",
            "nadšenie",
            "nahnúť",
            "nahrať",
            "nahradiť",
            "nahromadiť",
            "nahýbať",
            "najať",
            "naliehavosť",
            "nalíčiť",
            "nalíčiť sa",
            "namaľovať",
            "namaľovať sa",
            "namáhať sa",
            "namáhavý",
            "namietať",
            "namydliť",
            "namyslenosť",
            "namyslený",
            "nanešťastie",
            "naničhodník",
            "naniesť",
            "napadnutie",
            "napájať",
            "naplniť",
            "napodobniť",
            "napodobňovať",
            "napomenúť",
            "napomínať",
            "narásť",
            "narastať",
            "nariadiť",
            "nariekať",
            "narkoman",
            "narkotický",
            "narkotikum",
            "narodenie",
            "naskytnúť sa",
            "nasledovník",
            "nasledujúci",
            "nastať",
            "navoňať",
            "navrchu",
            "navštevovať",
            "naznačiť",
            "naznačovať",
            "nazvať",
            "nádoba",
            "nádor",
            "náklonnosť",
            "nákres",
            "námesačník",
            "námesačný",
            "námorný",
            "náplň",
            "národ",
            "národniarstvo",
            "národovec",
            "následnosť",
            "násobiť",
            "nebohý",
            "nebožtík",
            "nedôvera",
            "nedôverovať",
            "negramotný",
            "neha",
            "nemota",
            "nemý",
            "neplodnosť",
            "nepriateľský",
            "nepriateľstvo",
            "neresť",
            "nerešpektovať",
            "nerv",
            "nesmelý",
            "neurológ",
            "neurológia",
            "nevďačník",
            "nevďačnosť",
            "nevďačný",
            "neverný",
            "nevoľnosť",
            "očkovať",
            "obecenstvo",
            "obesiť",
            "obesiť sa",
            "obezita",
            "obézny",
            "obeta",
            "objahca",
            "obhajoba",
            "obhajovať",
            "obilný",
            "objať",
            "objasniť",
            "objímať",
            "obkľúčiť",
            "oblečený",
            "obliecť",
            "obliekať",
            "oblok",
            "oblúk",
            "obmedziť",
            "obohatiť",
            "obohacovať",
            "obraz",
            "obrazovka",
            "obrúčka",
            "obsadenie",
            "pľuť",
            "padák",
            "padúcnica",
            "pamflet",
            "panic",
            "panovník",
            "papuľa",
            "paragraf",
            "paralelne",
            "paralelný",
            "parcela",
            "výhovorka",
            "výkon",
            "výkrik",
            "výmena",
            "výnimočný",
            "výpočet",
            "výpoveď",
            "výrobca",
            "výslovnosť",
            "výskum",
            "výstrel",
            "vývoj",
            "výzor",
            "výzva",
            "výška",
            "výživa",
            "vzbura",
            "vzbúriť sa",
            "vzdelanie",
            "vzdelanosť",
            "vzdelaný",
            "vzdialený",
            "vzdialiť",
            "vzdych",
            "vzdychať",
            "vzdychnúť",
            "vzhľad",
            "vzlietnuť",
            "vzlykať",
            "vzlykot",
            "vznik",
            "vzniknúť",
            "vzor",
            "vzrušenie",
            "vzrušiť",
            "však",
            "začínať",
            "zaľúbený",
            "zaľúbiť sa",
            "zabaviť",
            "zabaviť sa",
            "zabávať",
            "zabávať sa",
            "zabiť sa",
            "zablúdiť",
            "zabočiť",
            "zabrániť"};
*/

/*
    "pokaziť sa",
            "pokaziť",
            "pokladnica",
            "pokojný",
            "pokračovať",
            "pokuta",
            "pokutovať",
            "pole",
            "položiť",
            "pomôcť",
            "ponáhľať sa",
            "ponúknuť",
            "popáliť sa",
            "poplach",
            "popoludnie",
            "poprieť",
            "poradie",
            "poradiť",
            "porcelán",
            "poriadok",
            "porovnať",
            "porucha",
            "porušiť",
            "posádka",
            "poschodie",
            "poskytnúť",
            "poslať",
            "postaviť",
            "postaviť sa",
            "postup",
            "poškodiť",
            "pošmyknúť sa",
            "pošta",
            "poštípať",
            "potiť sa",
            "potom",
            "potopiť ",
            "potopiť sa",
            "potravina",
            "potrebovať",
            "potrestať",
            "potvrdiť",
            "použiť",
            "používať",
            "povedať",
            "povinnosť",
            "povolenie",
            "povoliť",
            "povraz",
            "pozdĺž",
            "pozdraviť",
            "pozemok",
            "poznať",
            "pozerať sa",
            "poznámka",
            "pozvánka",
            "pozvať",
            "požiadať",
            "požičať",
            "pôda",
            "prasknúť",
            "prať",
            "pravdepodobne",
            "práve",
            "právo",
            "pravý",
            "pre",
            "prebudiť",
            "precestovať",
            "preč",
            "pred",
            "predávať",
            "predbehnúť",
            "predchádzajúci",
            "predísť",
            "predjedlo",
            "prednosť",
            "predný",
            "predok",
            "predpis",
            "predpísať",
            "predplatiť si",
            "predpokladať",
            "predstavenie",
            "predstaviť",
            "prehánka",
            "prehliadka",
            "prehnúť",
            "prehrať",
            "prehrávať",
            "prechádzať sa",
            "prechladnutie",
            "prechodný",
            "prejaviť sa",
            "prejaviť",
            "prejsť",
            "prejsť sa",
            "prekážať",
            "prekážka",
            "prekročiť",
            "prekvapiť",
            "preložiť",
            "prenajať",
            "prepáčiť",
            "prepadnúť",
            "prepichnúť",
            "prepustiť"
            */